name: Secrets example
on: push
env:
  token: ${{ secrets.secret_token }}

jobs:
  run-python:
    runs-on: ubuntu-latest
    steps:
      - name: Run Python Script
        run: |
          python -m pip install requests
          python today_append.py