name: Secrets example
on: push
env:
  token: ${{ secrets.secret_token }}

jobs:
  run-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run Python Script
        run: |
          python -m pip install --upgrade pip
          pip install requests
          pip install pandas
          pip install python-dateutil
          pip install datetime
          pip install openpyxl
          pip install numpy
          pip install Path
          python readjson.py