name: Secrets example
on: push
env:
  token: ${{ secrets.secret_token }}

jobs:
  run-python:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions\setup-python
        with:
          python-version: '3.11'
      - name: Run Python Script
        run: |
          python -m pip install requests
          python -m pip install json
          python -m pip install pandas
          python -m pip install datetime
          python today_append.py



